name: PHP Composer

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '30 4,11,23 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: report
      env:
        USERNAME: ${{ secrets.username }}
        PASSWORD: ${{ secrets.password }}
      run: php -f test.php '$USERNAME' '$PASSWORD'

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
