name: PHP Composer

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '30 4,11,23 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: test
      run: echo Hello,world!
    
    - name: report
      run: php -r 'phpinfo();'

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
